export enum VISIBILITY {
  AUTHENTICATED = 'VISIBILITY_AUTHENTICATED',
  NOT_AUTHENTICATED = 'VISIBILITY_NOT_AUTHENTICATED',
  OWNER = 'VISIBILITY_OWNER',
  PUBLIC = 'VISIBILITY_PUBLIC',
  PROTECTED = 'VISIBILITY_PROTECTED',
  SCHEDULED = 'VISIBILITY_SCHEDULED',
}
